name: Reusable GitHub Sync PR
description: |
  This action runs the pulumi preview when opening a PR.

inputs:
  work_dir:
    required: false
    description: 'Where the Pulumi config are located.'
  config_directory:
    required: false
    description: 'Where the Github config are located.'
  stack_name:
    required: true
    description: 'Pulumi stack name.'
  pulumi_access_token:
    required: true
    description: 'Secret for accessing Pulumi.'
  pulumi_command:
    required: true
    description: 'What command to run when running Pulumi action. Options: preview and up.(default: preview)'
    default: 'preview'
  comment_on_pr:
    required: false
    description: 'Used when doing a Pulumi preview for Pull Requests'
    default: 'false'
  gh_token:
    required: true
    description: 'GitHub Token with pull_request scope to be able to post comments in the PR'

runs:
  using: "composite"

  steps:
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: '${{ github.action_path }}/go.mod'
        check-latest: true
        cache-dependency-path: '${{ github.action_path }}/go.sum'

    - name: Copy config to run pulumi
      env:
        CONFIG_DIRECTORY: ${{ inputs.config_directory }}
        WORK_DIR: ${{ inputs.work_dir }}
      run: |
        cp -r ${CONFIG_DIRECTORY} $GITHUB_ACTION_PATH
        cp ${WORK_DIR}/Pulumi*.yaml $GITHUB_ACTION_PATH
      shell: bash

    - name: Go mod download
      run: go mod download
      working-directory: '${{ github.action_path }}'
      shell: bash

    - uses: pulumi/actions@9519177da243fd32cab35cdbf19cce1ab7472fcc # v6.2.0
      with:
        command: '${{ inputs.pulumi_command }}'
        stack-name: '${{ inputs.stack_name }}'
        refresh: false
        work-dir: '${{ github.action_path }}'
        comment-on-pr: ${{ inputs.comment_on_pr }}
        github-token: ${{ inputs.gh_token }}
        diff: true
        edit-pr-comment: true
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.pulumi_access_token }}
